### ISSUE TITLE
Firefox?

### ISSUE THREAD

**Issue by p8ron** [Kukiezi/messenger-pics-downloader#2]
Running it with the Chrome driver gives me the following: 

> > Welcome to Messenger_Pics_Downloader
> To change program settings go to config.json
> Do You want to load data from config? (y/n):y
> Exception occured! Will download all images gathered until exception. Check webdriver_error.txt for more details.
> Downloading images...
> Traceback (most recent call last):
>   File ".\__main__.py", line 5, in <module>
>     startDownloader()
>   File "C:\Users\Idriz\Documents\GitHub\messenger-pics-downloader\messenger_downloader.py", line 145, in startDownloader
>     itertools.repeat(data["folder_name"]), image_links))
> UnboundLocalError: local variable 'image_links' referenced before assignment
> 
> > Welcome to Messenger_Pics_Downloader
> To change program settings go to config.json
> Do You want to load data from config? (y/n):y
> [0323/210958.765:ERROR:network_change_notifier_win.cc(141)] WSALookupServiceBegin failed with: 0

> DevTools listening on ws://127.0.0.1:50808/devtools/browser/a1bd0b5d-57ac-476f-acbe-c2350546a589
> [0323/211000.407:ERROR:network_change_notifier_win.cc(141)] WSALookupServiceBegin failed with: 0
> 
> Logging` in to Facebook.com...
> 
> [0323/211007.772:INFO:CONSOLE(14)] "
> 
>   This is a browser feature intended for
>   developers. If someone told you to copy-paste
>    something here to enable a Facebook feature
>   or "hack" someone's account, it is a
>      scam and will give them access to your
>    Facebook account.
> 
> See https://www.facebook.com/selfxss for more information.
> ", source: https://www.facebook.com/rsrc.php/v3iqES4/yB/l/en_US/Q59O4osvQMx.js?_nc_x=Ij3Wp8lg5Kz (14)
> Logged in!
> Starting image source scrapping...
> [0323/211012.511:INFO:CONSOLE(14)] "
> 
>  This is a browser feature intended for
>  developers. If someone told you to copy-paste
>   something here to enable a Facebook feature
>   or "hack" someone's account, it is a
>   scam and will give them access to your
>   Facebook account.
> 
> See https://www.facebook.com/selfxss for more information.
> ", source: https://www.facebook.com/rsrc.php/v3iqES4/yB/l/en_US/Q59O4osvQMx.js?_nc_x=Ij3Wp8lg5Kz (14)
> Exception occured! Will download all images gathered until exception. Check webdriver_error.txt for more details.
> Downloading images...
> Traceback (most recent call last):
>   File ".\__main__.py", line 5, in <module>
>     startDownloader()
>   File "C:\Users\Idriz\Documents\GitHub\messenger-pics-downloader\messenger_downloader.py", line 145, in startDownloader
>     itertools.repeat(data["folder_name"]), image_links))
> UnboundLocalError: local variable 'image_links' referenced before assignment

While running it with the gecko driver gives at least something but still,not successful:

> PS C:\Users\Idriz\Downloads\messenger-pics-downloader> py .\__main__.py
Welcome to Messenger_Pics_Downloader
To change program settings go to config.json
Do You want to load data from config? (y/n):y
Logging in to Facebook.com...
Logged in!
Starting image source scrapping...
skipping 1 picture
skipping 2 picture
skipping 3 picture
skipping 4 picture
skipping 5 picture
skipping 6 picture
...
skipping 196 picture
skipping 197 picture
skipping 198 picture
skipping 199 picture
Getting image source: 1
Getting image source: 2
Getting image source: 3
Getting image source: 4
Getting image source: 5
Getting image source: 6
Getting image source: 7
Getting image source: 8
Getting image source: 9
Getting image source: 10
Getting image source: 11

Meanwhile it only saves 1 picture,and only if I put it to save source to txt,otherwise no download since it doesn't stop and goes on

I'll paste the webdriver_errors below:
Chrome:[webdriver_error.txt](https://github.com/Kukiezi/messenger-pics-downloader/files/4371721/webdriver_error.txt)

Gecko:
[webdriver_error.txt](https://github.com/Kukiezi/messenger-pics-downloader/files/4371668/webdriver_error.txt)

Since I'm not quite understanding of Python,I couldn't do much I'm sorry therefore I post here

**Comment by jakewilliami** [comment]
It looks like the Gecko driver is indeed accessing Facebook, but perhaps the driver is out of date.  Can you verify your geckodriver installation is up to date?  

Edit: alternatively, maybe @Kukiezi has an older version of Chrome that they were testing on for the scraping?
