### ISSUE TITLE
No module named "requests"

### ISSUE THREAD

**Issue by ilovebarney** [Kukiezi/messenger-pics-downloader#4]
I was trying to follow along the instructions, and as I was executing `python3 messenger-pics-downloader`, this pops up `Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "messenger-pics-downloader/__main__.py", line 1, in <module>
    from downloader import downloadImages
  File "messenger-pics-downloader/downloader.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'`

any workaround for this? thanks so much!

**Comment by demonium77** [comment]
I'm having the same issue. If someone has a fix that would be awesome :)

**Comment by SkourtsidisGiorgos** [comment]
Run in a cmd `pip install requests`
