### ISSUE TITLE
Error while trying to run 

### ISSUE THREAD

**Issue by Ynlay** [Kukiezi/messenger-pics-downloader#5]
I followed the instructions however whenever I try to run the program I get this error -->  

line 144, in startDownloader   pool.starmap(downloadImages, zip(itertools.repeat(current_dir),itertools.repeat(data["folder_name"]), image_links)) UnboundLocalError: local variable 'image_links' referenced before assignment

**Comment by akabab** [comment]
same issue here

**Comment by bystrzano4** [comment]
same here

**Comment by stefali1-dev** [comment]
same here

**Comment by jakewilliami** [comment]
Bump.  I am getting the same issue.

**Comment by jakewilliami** [comment]
Okay, this seems like a generic issue for most errors in this code.  The full stacktrace to my error *was*
```bash
$ python3 messenger-pics-downloader/
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning:
urllib3 (1.26.3) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Welcome to Messenger_Pics_Downloader
To change program settings go to config.json
Do You want to load data from config? (y/n):y
Exception occured! Will download all images gathered until exception. Check webdriver_error.txt for more details.
Downloading images...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "messenger-pics-downloader/__main__.py", line 5, in <module>
    startDownloader()
  File "messenger-pics-downloader/messenger_downloader.py", line 145, in startDownloader
    itertools.repeat(data["folder_name"]), image_links))
UnboundLocalError: local variable 'image_links' referenced before assignment
```
So I had a look in `messenger-pics-downloader/webdriver_error.txt` and:
```bash
$ cat messenger-pics-downloader/webdriver_error.txt
Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
```
My `chromedriver` _is_ in my `PATH`, so I found that you may need to [change the path in the python code to be absolute](https://stackoverflow.com/a/29858817/12069968).  However, on my macOS machine, I also had to add the [path to the Google Chrome executable](https://stackoverflow.com/a/46027522/12069968).

Now this is what I changed `driver.py` to look like:
```python3
from selenium import webdriver
import os

def initializeDriver(directory, binary_location):
    options = webdriver.ChromeOptions()
    prefs = {"profile.default_content_setting_values.notifications": 2}
    options.add_argument("--headless")
    options.add_argument("--mute-audio")
    options.add_argument("--kiosk")
    options.add_experimental_option("prefs", prefs)
    options.binary_location = binary_location
    driver = webdriver.Chrome(
        f"{directory}/chromedriver", options=options)
    return driver
```
(Notice it has an option for `binary_location`: this is where the Google Chrome binary is).  And I have changed `messenger_downloader.py` with the following:
  1. Add the following two variable definitions before defining `startDownloader`:
    ```python3
    chrome_binary_location = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
    chrome_driver_binary_dir = "/usr/local/bin/" # run `which chromedriver` to see where in path this is located
    ```
  2. In the first `try` statement in the definition of `startDownloader`, I changed `driver = initializeDriver(current_dir)` to `driver = initializeDriver(chrome_driver_binary_dir, chrome_binary_location)`.

These two things helped me to overcome this above error.  _However_, I now have another error...
```bash
$ python3 messenger-pics-downloader/
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.3) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Welcome to Messenger_Pics_Downloader
To change program settings go to config.json
Do You want to load data from config? (y/n):y
Logging in to Facebook.com...
Logged in!
Starting image source scrapping...
Exception occured! Will download all images gathered until exception. Check webdriver_error.txt for more details.
Downloading images...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "messenger-pics-downloader/__main__.py", line 5, in <module>
    startDownloader()
  File "messenger-pics-downloader/messenger_downloader.py", line 148, in startDownloader
    itertools.repeat(data["folder_name"]), image_links))
UnboundLocalError: local variable 'image_links' referenced before assignment

$ cat messenger-pics-downloader/webdriver_error.txt
Message: no such element: Unable to locate element: {"method":"css selector","selector":"._3m31"}
  (Session info: headless chrome=89.0.4389.72)
```

**Comment by Nealon01** [comment]
> These two things helped me to overcome this above error. _However_, I now have another error...

I'm at the same error now... anyone able to get past this?

**Comment by jakewilliami** [comment]
Hey @Nealon01, unfortunately I did not end up using Python to do this.  However, you can download this data on Facebook.

Go to Facebook > Settings & Privacy > Settings > Your Facebook Information > Download Your Information.  Now deselect all, and tick Messages.  It may take a couple of hours to download these, but once they are done, you can extract all of the images:

```bash
cd ~/Downloads/
mkdir all-facebook-data
unzip facebook-* -d all-facebook-data/
mkdir all-images
find facebook-data/ -type f \( -iname \*.jpg -o -iname \*.png \) -exec cp {} all-images/ \;
```

Now the `all-images` directory will have all of the images from all messages you've sent.  You can do something more complicated to extract images given the person with whom you are having the conversation:

```bash
mkdir people
find facebook-data/ -type f \( -iname \*.jpg -o -iname \*.png \) | while IFS= read -r file; do 
    PHOTODIR="$(dirname "$file")"
    PHOTODIRONLY="$(basename "$PHOTODIR")"
    if [[ "$PHOTODIRONLY" == "photos" ]]; then 
        PERSONDIR="$(dirname "$PHOTODIR")"
        PERSONDIRONLY="$(basename "$PERSONDIR")"
        arrPERSON=(${PERSONDIRONLY//_/ })
        PERSON="${arrPERSON[0]}"
        if [[ ! -d people/"$PERSON" ]]; then
            mkdir people/"$PERSON"
        fi
        cp "$file" people/"$PERSON"/
    fi
done
```

Depending on how much you use Facebook, both of these will take a while to run...

I hope this helps, but sorry it is not as programmatic as the python script.  I think Facebook it notoriously difficult to scrape, unfortunately.  At least for me, no Facebook scraper has actually worked for me.  All the best!
